#!/usr/bin/env python
import sys
import pickle
import re

stub = sys.argv
try:
    filename = stub[1]
except:
    print "usage: {} <filename> [<test>]".format(stub[0])
    exit(1)
stub.append(None)
test = stub[2]

with open(filename, "rb") as fobj:
    tests = pickle.load(fobj)

for item in tests:
    if test is None or re.search(test, item):
        print '>>>', repr(item)
        print repr(tests[item])
